# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Objective_C_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'mParticle-Apple-SDK', '7.14.0'
  # Pods for Objective_C_App

end
